use_frameworks!

source 'https://github.com/artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'LZAddressPicker_Example' do
  pod 'LZAddressPicker', :path => '../'
  pod 'MJExtension'
  target 'LZAddressPicker_Tests' do
    inherit! :search_paths
    
  end
end
