use_frameworks!

source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

target 'LZAddressPicker_Example' do
  pod 'LZAddressPicker', :path => '../'
  pod 'MJExtension'
  target 'LZAddressPicker_Tests' do
    inherit! :search_paths
    
  end
end
